sudo: false
language: node_js
node_js:
  - "node"
cache:
  directories:
    - ~/.npm
script:
  # - npm test
  - npm run docs
notifications:
  email: false
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: out
  on:
    branch: master
